apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-config-master
  namespace: jenkins
data:
  config.json: |-
    {
      "credHelpers": {
        "harbor.rke2-app.km.test": "harbor-km-test-robot"
        "registry1.dso.mil": "registry1-dso-mil-km"
        "registry.redhat.com": "rhel-containers-j7"
      }
    }
